name: Generate OIDC Token

on:
  workflow_dispatch:

jobs:
  generate-token:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Generate OIDC Token
        id: oidc
        uses: actions/github-script@v6
        with:
          script: |
            const token = await github.rest.actions.getOrgOidcCustomClaimTemplate({
              org: context.repo.owner
            });
            console.log('OIDC Token:', token.data);
            return token.data;

      - name: Display Token
        run: |
          echo "=== OIDC Token ==="
          echo "${{ steps.oidc.outputs.result }}"
          echo "=================="