name: Get OIDC Token
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  get-token:
    runs-on: ubuntu-latest
    steps:
      - name: Get OIDC Token
        run: |
          TOKEN=$(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=https://iam.googleapis.com/projects/PROJECT_NUMBER/locations/global/workloadIdentityPools/POOL_ID/providers/PROVIDER_ID" \
            | jq -r '.value')
          
          echo "$TOKEN" > token.txt

      - name: Upload token as artifact
        uses: actions/upload-artifact@v4
        with:
          name: oidc-token
          path: token.txt