name: Get OIDC Token
on:
  workflow_dispatch:  # Manual trigger

permissions:
  id-token: write   # Required for OIDC
  contents: read

jobs:
  get-token:
    runs-on: ubuntu-latest
    steps:
      - name: Get OIDC Token
        run: |
          # Request token from GitHub's OIDC provider
          TOKEN=$(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=https://iam.googleapis.com/projects/PROJECT_NUMBER/locations/global/workloadIdentityPools/POOL_ID/providers/PROVIDER_ID" \
            | jq -r '.value')
          
          echo "Token (first 50 chars): ${TOKEN:0:50}..."
          echo "Full token length: ${#TOKEN}"
          
          # Decode to see claims (optional)
          echo "$TOKEN" | cut -d'.' -f2 | base64 -d 2>/dev/null | jq .